### ISSUE TITLE
Gamepad not detect

### ISSUE THREAD

**Issue by mallynoshow** [martinx72/GPiMatePlusHowTo#3]
Hello

Hello

I can't get emulationstation to detect the pad or buttons. It only worked the first two times I started the console

Thanks

**Comment by martinx72** [comment]
It sounds like the cartridge pin aligment issue, please make sure the cartridge is plugged into the slot porperly.

**Comment by mallynoshow** [comment]
Hello there

I have checked the cartridge fit and it is correct. I have no problem with the original GPI cartridge. In fact I have two cartridges of Retroflag that work perfectly with two different images. In the Mate Plus 4 EmulatioinStation does not go beyond the gamepad request. I have tried leaving the minimum settings, without rotating the screen. But the same thing happens. I have tried several different sd's. Now I have a 64gb Sandisk, same problem.

Thanks.

**Comment by mallynoshow** [comment]
I found it! It was the raspberry module that was not properly fitted to the GPI cartriidge.

Thanks!!

**Comment by andypiper** [comment]
@mallynoshow how was the CM4 not properly fitted? I’m having an issue where the gamepad buttons are not being detected in ES and I’m wondering if I’ve done something wrong. I’ve taken the CM4 off and reseated it, but the problem remains.

**Comment by martinx72** [comment]
> @mallynoshow how was the CM4 not properly fitted? I’m having an issue where the gamepad buttons are not being detected in ES and I’m wondering if I’ve done something wrong. I’ve taken the CM4 off and reseated it, but the problem remains.

The pin alignment on the cartridge slot is not so well even with the officially cart pcb. I would suggest to make sure the cart cartridge pin fits the pins on the cart-slot. As USB go over there and if one is not perfect connection you lost the gamepad.

**Comment by mallynoshow** [comment]
It was the pin alignment, be carefull not to shake the cartridge. If the problem remains try with a new sd image.
