### ISSUE TITLE
Issues with rotation and gamepad detection

### ISSUE THREAD

**Issue by andypiper** [martinx72/GPiMatePlusHowTo#5]
I’ve installed Retropie 4.7.1 on a 128Gb SanDisk card and applied the updates listed here, in order.

I’ve also tried reflashing and re-running through the config steps, exactly as written here, several times.

I configured Wifi and ssh by adding files to the /boot partition before booting the CM4 Lite. The card connects to my wifi and I was able to ssh in to make the changes to the config scripts.

From the default setup in the config here, I can only get the system to repeatedly reboot when ES was starting, so I ended up ssh’ing in and modifying some of the config manually when the CM4 was not connected to the GPi Case.

I was not able to get ES to detect the buttons at all, so I modified the ES config to not attempt to auto config, and managed to get into the UI properly.

Current status:

- The system boots. Initially the tty1 console output is sideways (90 degrees counter-clockwise), but it corrects itself to vertical after a few seconds.
- The Retropie splash screen is 90 degress counter-clockwise, even though I updated the config file.
- sound works (there’s a sound when I navigate through the Retropie config menu list)
- ES front end shows the Retropie config screen (correct rotation). A and B buttons work and I can get to the Retropie config menu and press B to get back to the top screen, or press A to enter a menu option. Once into the blue console menu for configuring an option, none of the buttons work.

I’ve tried re-seating the CM4 in the carrier board a couple of times, and I’ve confirmed that the cartridge is making good contact. The CM4 is the correct way up.

Questions:
- What should the complete set of config scripts look like? Can anyone with a working setup share the /boot/config.txt and /boot/cmdline.txt and /opt/retropie/config/all (all files) contents? (I guess especially `es_input.cfg` should be relevant?)
- What should `lsusb` and `lsdev` show? I read somewhere in the Recalbox setup that the GPi case is the same as an XBox 360 controller, not sure if this is relevant as I try to get this to work, I just would like to understand what I should be seeing in my system. 
- What shoud a working `dmesg` output look like after booting?

- (unrelated to functionality) is there a way to configure a framebuffer boot output with smaller font for the screen, or have the system boot with the correct screen rotation from the start?

The PiZero setup in the original cartridge is working fine (using Recalbox), so I do not believe there are any issues with the Retroflag GPi Case hardware.

I’m going to try going through everything again right now, but this is taking more time than I expected!

**Comment by andypiper** [comment]
OK. Freshly flashed to the SD card, and then the `config.txt` settings applied and overlays installed.

System boots (sideways - `cmdline.txt` not applied yet) and resizes the filesystem. Reboots (sideways). Retroarch splash (sideways). System powers off (well, the lights go off on the GPiMate+ card, and screen goes blank).

Now going to try making the other config changes.

**Comment by andypiper** [comment]
I'm inconsistently getting to the main ES screen with 0 or 1 controller detected. When I have done so with 1 controller, I can configure it (it does show up as Xbox 360). I'm not consistently able to get the cartridge to start.

What do the green and red lights on the GPiMate+ card mean? For example, if the screen comes on and the green light blinks every second, what is that saying? It is not starting in that case, so I think it's an SD card issue?

I'm about to try another reflash.

**Comment by martinx72** [comment]
> I'm inconsistently getting to the main ES screen with 0 or 1 controller detected. When I have done so with 1 controller, I can configure it (it does show up as Xbox 360). I'm not consistently able to get the cartridge to start.

I replied your other report, the gamepad is in fact a usb device. Simply your cart is not plugged perfectly somehow.

> What do the green and red lights on the GPiMate+ card mean? For example, if the screen comes on and the green light blinks every second, what is that saying? It is not starting in that case, so I think it's an SD card issue?

Green/Red lights are same a Pi4 

https://raspberrytips.com/green-and-red-light-on-raspberry-pi/
